// Goofy challenge: silly, safe things to do at home. Order is stable (the database stores the position), so only add to the end.
export interface Goofy { title: string; text: string }
export const GOOFY: Goofy[] = [
  { title: "OPERATION ANGRY CHICKEN", text: "Cross the room clucking and flapping like a very serious chicken." },
  { title: "HURRICANE HALLWAY", text: "Walk across the room like you are fighting through 100-mile-an-hour wind." },
  { title: "ONE-LEG EXPRESS", text: "Hop carefully from one side of the room to the other on one foot." },
  { title: "POP-STAR EMERGENCY", text: "Perform 15 seconds of your favorite song like you are headlining a sold-out stadium." },
  { title: "DRAMATIC ENTRANCE", text: "Leave the room, then come back in with the most ridiculously dramatic entrance possible." },
  { title: "SLOW-MOTION HERO", text: "Walk across the room in extreme slow motion like the final scene of an action movie." },
  { title: "ROBOT MALFUNCTION", text: "Act like a robot whose controls are completely malfunctioning for 20 seconds." },
  { title: "INVISIBLE FLOOR", text: "Cross the room while pretending the floor is covered in invisible obstacles." },
  { title: "TINY DINOSAUR", text: "Walk around for 20 seconds pretending you are the world's smallest, angriest dinosaur." },
  { title: "MOON GRAVITY", text: "Cross the room as if gravity is only one-sixth as strong." },
  { title: "SECRET AGENT", text: "Sneak across the room like lasers are everywhere and one wrong move sets off the alarm." },
  { title: "ALIEN GREETING", text: "Walk up to a family member and invent the strangest friendly alien greeting you can." },
  { title: "RUNWAY DISASTER", text: "Do a 15-second fashion runway walk that gets more ridiculous with every step." },
  { title: "STATUE GLITCH", text: "Freeze in the weirdest pose you can hold safely for 15 seconds." },
  { title: "EVIL GENIUS", text: "Give your best evil-genius laugh, then immediately switch to your nicest smile." },
  { title: "INVISIBLE CAPE", text: "Pretend your invisible superhero cape keeps getting caught on everything for 20 seconds." },
  { title: "PENGUIN PROTOCOL", text: "Waddle across the room like a penguin late for an important meeting." },
  { title: "ZOMBIE MONDAY", text: "Walk across the room like a zombie who just woke up for school on Monday." },
  { title: "FLOOR IS JELLO", text: "Cross the room as if the entire floor is wobbling like gelatin." },
  { title: "GIANT SHOES", text: "Walk ten steps like your shoes suddenly weigh 50 pounds each." },
  { title: "MIME BOX", text: "Pretend you are trapped inside an invisible box for 20 seconds." },
  { title: "SPORTS ANNOUNCER", text: "Narrate something completely ordinary nearby like it is the championship game." },
  { title: "ROYAL DECREE", text: "Announce what you want for dinner like a king or queen issuing a royal decree." },
  { title: "NINJA SNEEZE", text: "Sneak across the room like a ninja who is desperately trying not to sneeze." },
  { title: "BROKEN ESCALATOR", text: "Pretend you are walking up an escalator that keeps changing direction." },
  { title: "GIANT BABY", text: "Take ten steps like a giant baby learning to walk for the first time." },
  { title: "UNDERWATER MODE", text: "Move around for 20 seconds like you are deep underwater." },
  { title: "INVISIBLE DOG", text: "Pretend an enormous invisible dog is dragging you across the room on a leash." },
  { title: "WEATHER REPORT", text: "Give a dramatic 15-second weather report about completely ridiculous weather." },
  { title: "SUPERHERO LANDING", text: "Do your safest, most dramatic superhero arrival pose and hold it for five seconds." },
  { title: "BACKWARDS DAY", text: "Say your name, favorite food, and favorite color in reverse order." },
  { title: "GAME SHOW HOST", text: "Introduce a family member like they are the grand-prize contestant on a game show." },
  { title: "SPAGHETTI ARMS", text: "Walk around for 15 seconds as if your arms have suddenly turned into cooked spaghetti." },
  { title: "SUSPICIOUS POTATO", text: "Pretend you just discovered that an ordinary object in the room is secretly a suspicious potato." },
  { title: "TIME TRAVELER", text: "Act shocked by three ordinary modern objects as if you just arrived from the year 1426." },
  { title: "BOSS BATTLE", text: "Pick a pillow or harmless object and dramatically announce it as the final boss. No hitting required." },
  { title: "SILENT DISCO", text: "Dance as wildly as you can for 15 seconds with absolutely no music playing." },
  { title: "VOICE GLITCH", text: "Say one normal sentence in three ridiculous voices." },
  { title: "MAGNET BOOTS", text: "Take ten steps as if powerful magnets keep sticking your shoes to the floor." },
  { title: "VICTORY LAP", text: "Do a slow, safe walking lap around the room celebrating like you just won the most important contest in the universe." },
  { title: "SLOW-MOTION REPLAY", text: "Pick up a pencil in super slow motion, like an instant replay of a famous goal." },
  { title: "ROBOT BREAKFAST", text: "Pretend to be a robot eating breakfast. Say beep boop after every bite." },
  { title: "CHEF DRAMA", text: "Cook an invisible meal while narrating like a dramatic cooking show host." },
  { title: "SOCK PUPPET", text: "Make a sock a puppet and have it introduce you to the family." },
  { title: "SNEAKY SNAIL", text: "Move across the room as slowly as a snail on a very important mission." },
  { title: "TREASURE MAP", text: "Draw a quick treasure map of your room, then follow it to find a hidden snack or item." },
  { title: "ANIMAL TRANSLATOR", text: "Pretend you can understand a pet or stuffed animal and translate what it is saying." },
  { title: "OPPOSITE DAY", text: "Say the opposite of what you mean for one whole minute, nicely and safely." },
  { title: "CHEERLEADER", text: "Invent a three-second cheer for the nearest piece of furniture." },
  { title: "MARSHMALLOW MARCH", text: "March in place for 15 seconds as if your feet are made of marshmallows." },
  { title: "GIGGLE CHALLENGE", text: "Try to say 'purple pickle parade' five times without smiling." },
  { title: "HUMAN SPRINKLER", text: "Spin your arms slowly like a garden sprinkler while standing in one spot for 10 seconds." },
  { title: "LIBRARY WHISPER", text: "Whisper-shout a silly sentence as dramatically as you can without making any noise." },
  { title: "PIRATE TALK", text: "Talk like a pirate for one whole minute. Yo ho ho!" },
  { title: "TOY STORY NARRATOR", text: "Narrate a stuffed animal's day like a nature documentary." },
  { title: "STATUE SHOW", text: "Become a statue of a famous pose from a sport and hold it for ten seconds." },
  { title: "NEWSCASTER", text: "Announce today's top story: something small and silly that happened in your house." },
  { title: "BUBBLE WALK", text: "Walk around pretending you are inside a giant floating bubble. Do not pop it." },
  { title: "SUPER SLOW HIGH FIVE", text: "Give someone the slowest high five in the history of high fives." },
  { title: "MYSTERY CHEF", text: "Name a made-up food with the silliest name you can think of and describe how it tastes." },
  { title: "SILLY SIGNATURE", text: "Write your name with your non-writing hand and add a fancy flourish." },
  { title: "ELEVATOR MUSIC", text: "Hum your own elevator music while riding an invisible elevator for 15 seconds." },
  { title: "TEACHER FOR A MINUTE", text: "Teach an imaginary class how to tie a shoe, in an extremely serious voice." },
  { title: "DANCE OF THE SPOON", text: "Hold a spoon like a microphone and sing one line of a song in a funny voice." },
];

export const GOOFY_REWARD = 5;
export interface GoofyState { status: 'accepted' | 'done' | 'skipped' | null; prompt: number | null; doneToday: number }
