-- Generated by scripts/seed-questions.mjs from content/questions.json. Do not edit by hand.
insert into public.questions (id, subject, grade, skill, difficulty, prompt, choices) values
  ('m5-001', 'math', 5, 'fractions', 1, 'What is 1/2 + 1/4?', '["3/4","2/6","1/4","2/8"]'::jsonb),
  ('m5-002', 'math', 5, 'fractions', 2, 'What is 2/3 + 1/6?', '["3/9","5/6","3/6","2/9"]'::jsonb),
  ('m5-003', 'math', 5, 'fractions', 2, 'What is 3/4 - 1/3?', '["2/1","1/12","5/12","2/7"]'::jsonb),
  ('m5-004', 'math', 5, 'fractions', 2, 'What is 1/2 x 3/4?', '["4/6","3/6","5/8","3/8"]'::jsonb),
  ('m5-005', 'math', 5, 'fractions', 3, 'What is 3/5 of 20?', '["12","15","8","60"]'::jsonb),
  ('m5-006', 'math', 5, 'decimals', 1, 'What is 3.4 + 2.75?', '["5.15","6.15","6.25","5.79"]'::jsonb),
  ('m5-007', 'math', 5, 'decimals', 2, 'What is 8.2 - 3.65?', '["5.55","4.65","4.55","5.45"]'::jsonb),
  ('m5-008', 'math', 5, 'decimals', 2, 'What is 0.6 x 0.3?', '["1.8","0.9","0.018","0.18"]'::jsonb),
  ('m5-009', 'math', 5, 'decimals', 1, 'Which number is the greatest?', '["0.5","0.45","0.405","0.054"]'::jsonb),
  ('m5-010', 'math', 5, 'place-value', 1, 'In the number 4,732,100, what is the value of the digit 7?', '["70,000","700,000","7,000","7,000,000"]'::jsonb),
  ('m5-011', 'math', 5, 'place-value', 2, 'In the number 12.358, which place is the digit 5 in?', '["tenths","thousandths","hundredths","ones"]'::jsonb),
  ('m5-012', 'math', 5, 'place-value', 2, 'What is 3.27 x 100?', '["32.7","3,270","0.327","327"]'::jsonb),
  ('m5-013', 'math', 5, 'volume', 1, 'A box is 4 units long, 3 units wide and 2 units tall. What is its volume?', '["24 cubic units","9 cubic units","14 cubic units","12 cubic units"]'::jsonb),
  ('m5-014', 'math', 5, 'volume', 2, 'A cube has sides of 5 cm. What is its volume?', '["15 cubic cm","125 cubic cm","25 cubic cm","150 cubic cm"]'::jsonb),
  ('m5-015', 'math', 5, 'volume', 3, 'A box has a volume of 360 cubic cm, a length of 10 cm and a width of 6 cm. How tall is it?', '["5 cm","8 cm","6 cm","36 cm"]'::jsonb),
  ('m5-016', 'math', 5, 'order-of-operations', 1, 'What is 3 + 4 x 2?', '["14","10","24","11"]'::jsonb),
  ('m5-017', 'math', 5, 'order-of-operations', 2, 'What is (12 - 4) / 2 + 1?', '["5","3","7","9"]'::jsonb),
  ('m5-018', 'math', 5, 'word-problems', 2, 'A student buys 3 notebooks at $2.50 each and one pen for $1.25. What is the total cost?', '["$8.25","$8.75","$3.75","$9.75"]'::jsonb),
  ('m5-019', 'math', 5, 'word-problems', 3, 'A recipe uses 3/4 cup of sugar for one batch. How many cups of sugar are needed for 4 batches?', '["2 cups","3 1/4 cups","3 cups","12 cups"]'::jsonb),
  ('m5-020', 'math', 5, 'word-problems', 3, 'A rope is 5 1/2 meters long. If 2 3/4 meters are cut off, how much rope is left?', '["3 1/4 meters","2 1/4 meters","3 3/4 meters","2 3/4 meters"]'::jsonb),
  ('m6-001', 'math', 6, 'ratios', 1, 'The ratio of red to blue marbles is 3:5. If there are 15 red marbles, how many blue marbles are there?', '["25","9","20","18"]'::jsonb),
  ('m6-002', 'math', 6, 'ratios', 2, 'A car travels 120 miles in 3 hours at a steady speed. What is its unit rate?', '["36 miles per hour","40 miles per hour","360 miles per hour","30 miles per hour"]'::jsonb),
  ('m6-003', 'math', 6, 'ratios', 2, 'Which ratio is equivalent to 4:6?', '["3:2","2:4","2:3","8:10"]'::jsonb),
  ('m6-004', 'math', 6, 'ratios', 3, 'Paint is mixed with blue and white in a 2:5 ratio. How many cups of white are in 14 cups of paint?', '["4","8","12","10"]'::jsonb),
  ('m6-005', 'math', 6, 'percents', 1, 'What is 25% of 80?', '["20","25","40","32"]'::jsonb),
  ('m6-006', 'math', 6, 'percents', 2, 'What is 15% of 60?', '["6","9","90","15"]'::jsonb),
  ('m6-007', 'math', 6, 'percents', 2, 'A student got 18 out of 24 questions right. What percent is that?', '["70%","80%","75%","66%"]'::jsonb),
  ('m6-008', 'math', 6, 'percents', 3, 'A $40 shirt is 20% off. What is the sale price?', '["$8","$20","$36","$32"]'::jsonb),
  ('m6-009', 'math', 6, 'integers', 1, 'What is -3 + (-5)?', '["-8","8","-2","2"]'::jsonb),
  ('m6-010', 'math', 6, 'integers', 2, 'What is 4 - 9?', '["5","-5","-13","13"]'::jsonb),
  ('m6-011', 'math', 6, 'integers', 2, 'The temperature is -6 degrees and rises 10 degrees. What is the new temperature?', '["-16 degrees","-4 degrees","4 degrees","16 degrees"]'::jsonb),
  ('m6-012', 'math', 6, 'equations', 1, 'Solve for x: x + 7 = 15', '["22","7","9","8"]'::jsonb),
  ('m6-013', 'math', 6, 'equations', 2, 'Solve for n: 3n = 36', '["12","108","33","9"]'::jsonb),
  ('m6-014', 'math', 6, 'equations', 3, 'Solve for x: 2x + 5 = 17', '["11","6","7","5"]'::jsonb),
  ('m6-015', 'math', 6, 'area-triangle', 2, 'A triangle has a base of 10 units and a height of 6 units. What is its area?', '["60 square units","16 square units","30 square units","32 square units"]'::jsonb),
  ('m6-016', 'math', 6, 'area-triangle', 3, 'A triangle has an area of 24 square cm and a base of 8 cm. What is its height?', '["3 cm","12 cm","4 cm","6 cm"]'::jsonb),
  ('m6-017', 'math', 6, 'mean-median', 1, 'What is the mean of 4, 6, 8, 10 and 12?', '["8","6","10","40"]'::jsonb),
  ('m6-018', 'math', 6, 'mean-median', 2, 'What is the median of 3, 9, 4, 7 and 12?', '["4","7","9","6"]'::jsonb),
  ('m6-019', 'math', 6, 'exponents', 1, 'What is 6 squared (6^2)?', '["12","26","36","8"]'::jsonb),
  ('m6-020', 'math', 6, 'exponents', 2, 'What is 2^5?', '["10","25","16","32"]'::jsonb)
on conflict (id) do update set subject = excluded.subject, grade = excluded.grade, skill = excluded.skill,
  difficulty = excluded.difficulty, prompt = excluded.prompt, choices = excluded.choices;
insert into public.question_keys (question_id, answer, explanation) values
  ('m5-001', 0, 'Rename 1/2 as 2/4, then 2/4 + 1/4 = 3/4.'),
  ('m5-002', 1, 'Rename 2/3 as 4/6, then 4/6 + 1/6 = 5/6.'),
  ('m5-003', 2, 'Use twelfths: 9/12 - 4/12 = 5/12.'),
  ('m5-004', 3, 'Multiply the tops (1x3=3) and the bottoms (2x4=8) to get 3/8.'),
  ('m5-005', 0, 'Find 1/5 of 20 (which is 4), then multiply by 3 to get 12.'),
  ('m5-006', 1, 'Line up the decimal points: 3.40 + 2.75 = 6.15.'),
  ('m5-007', 2, 'Write 8.20 - 3.65 and subtract with regrouping to get 4.55.'),
  ('m5-008', 3, '6 x 3 = 18, and two decimal places in total gives 0.18.'),
  ('m5-009', 0, 'Write them with three places: 0.500 is larger than 0.450, 0.405 and 0.054.'),
  ('m5-010', 1, 'The 7 is in the hundred-thousands place, so its value is 700,000.'),
  ('m5-011', 2, 'After the decimal point the places are tenths, hundredths, thousandths; 5 is second.'),
  ('m5-012', 3, 'Multiplying by 100 moves the decimal point two places right.'),
  ('m5-013', 0, 'Volume = length x width x height = 4 x 3 x 2 = 24.'),
  ('m5-014', 1, 'Volume of a cube is 5 x 5 x 5 = 125 cubic centimeters.'),
  ('m5-015', 2, 'Length x width = 60, and 360 divided by 60 is 6.'),
  ('m5-016', 3, 'Multiply first (4 x 2 = 8), then add 3 to get 11.'),
  ('m5-017', 0, 'Parentheses first: 8, then 8 / 2 = 4, then 4 + 1 = 5.'),
  ('m5-018', 1, 'Notebooks cost 3 x 2.50 = 7.50, and 7.50 + 1.25 = 8.75.'),
  ('m5-019', 2, '4 x 3/4 = 12/4 = 3 cups.'),
  ('m5-020', 3, '5 1/2 = 5 2/4, and 5 2/4 - 2 3/4 = 2 3/4.'),
  ('m6-001', 0, '15 is 3 x 5, so blue is 5 x 5 = 25.'),
  ('m6-002', 1, '120 divided by 3 is 40 miles for each hour.'),
  ('m6-003', 2, 'Divide both parts of 4:6 by 2 to get 2:3.'),
  ('m6-004', 3, 'There are 7 parts in all, so each part is 2 cups, and white is 5 x 2 = 10.'),
  ('m6-005', 0, '25% is one fourth, and 80 divided by 4 is 20.'),
  ('m6-006', 1, '10% of 60 is 6 and 5% is 3, so 15% is 9.'),
  ('m6-007', 2, '18/24 simplifies to 3/4, which equals 75%.'),
  ('m6-008', 3, '20% of 40 is 8, and 40 - 8 = 32.'),
  ('m6-009', 0, 'Adding two negatives gives a more negative number: -8.'),
  ('m6-010', 1, 'Counting 9 steps down from 4 lands on -5.'),
  ('m6-011', 2, '-6 + 10 = 4.'),
  ('m6-012', 3, 'Subtract 7 from both sides: x = 15 - 7 = 8.'),
  ('m6-013', 0, 'Divide both sides by 3: n = 12.'),
  ('m6-014', 1, 'Subtract 5 to get 2x = 12, then divide by 2 to get x = 6.'),
  ('m6-015', 2, 'Area = 1/2 x base x height = 1/2 x 10 x 6 = 30.'),
  ('m6-016', 3, '24 = 1/2 x 8 x h, so 24 = 4h and h = 6.'),
  ('m6-017', 0, 'The sum is 40, and 40 divided by 5 numbers is 8.'),
  ('m6-018', 1, 'In order: 3, 4, 7, 9, 12. The middle number is 7.'),
  ('m6-019', 2, '6^2 means 6 x 6, which equals 36.'),
  ('m6-020', 3, '2^5 = 2 x 2 x 2 x 2 x 2 = 32.')
on conflict (question_id) do update set answer = excluded.answer, explanation = excluded.explanation;
insert into public.questions (id, subject, grade, skill, difficulty, prompt, choices) values
  ('v5-001', 'vocab', 5, 'prefixes', 1, 'The prefix un- in the word unhappy means:', '["not","again","before","too much"]'::jsonb),
  ('v5-002', 'vocab', 5, 'prefixes', 1, 'The prefix re- in the word rewrite means:', '["not","again","under","before"]'::jsonb),
  ('v5-003', 'vocab', 5, 'prefixes', 2, 'The prefix pre- in the word preview means:', '["after","again","before","between"]'::jsonb),
  ('v5-004', 'vocab', 5, 'suffixes', 1, 'The suffix -less in the word hopeless means:', '["full of","able to","more","without"]'::jsonb),
  ('v5-005', 'vocab', 5, 'suffixes', 2, 'The suffix -able in the word readable means:', '["can be","without","one who","full of"]'::jsonb),
  ('v5-006', 'vocab', 5, 'roots', 2, 'The root aqua, as in aquarium, means:', '["fire","water","earth","air"]'::jsonb),
  ('v5-007', 'vocab', 5, 'roots', 3, 'The root bio, as in biology, means:', '["sound","earth","life","writing"]'::jsonb),
  ('v5-008', 'vocab', 5, 'synonyms', 1, 'Which word is a synonym for huge?', '["tiny","quick","silent","enormous"]'::jsonb),
  ('v5-009', 'vocab', 5, 'synonyms', 2, 'Which word means about the same as rapid?', '["swift","gentle","careful","sleepy"]'::jsonb),
  ('v5-010', 'vocab', 5, 'antonyms', 2, 'Which word is the opposite of ancient?', '["old","modern","historic","huge"]'::jsonb),
  ('v5-011', 'vocab', 5, 'antonyms', 2, 'Which word is the opposite of generous?', '["kind","wealthy","selfish","giving"]'::jsonb),
  ('v5-012', 'vocab', 5, 'multiple-meaning', 2, 'Which meaning of bank fits: We had a picnic on the bank of the river.', '["a place that keeps money","to tilt an airplane","a row of switches","the land beside a river"]'::jsonb),
  ('v5-013', 'vocab', 5, 'multiple-meaning', 3, 'In the sentence The scientist had a novel idea, what does novel mean?', '["new and original","a long book","boring","stolen"]'::jsonb),
  ('v5-014', 'vocab', 5, 'context-clues', 2, 'The desert was so arid that no rain had fallen for months. What does arid mean?', '["very cold","very dry","very large","very windy"]'::jsonb),
  ('v5-015', 'vocab', 5, 'context-clues', 2, 'Because he was famished after the long hike, he ate three sandwiches. What does famished mean?', '["very tired","very thirsty","very hungry","very cold"]'::jsonb),
  ('v5-016', 'vocab', 5, 'context-clues', 3, 'Lena was reluctant to jump into the cold lake, so she stood at the edge for a long time. What does reluctant mean?', '["eager","excited","tired","unwilling"]'::jsonb),
  ('v5-017', 'vocab', 5, 'figurative-language', 1, 'What does the phrase busy as a bee mean?', '["very busy","fond of honey","easily frightened","very small"]'::jsonb),
  ('v5-018', 'vocab', 5, 'figurative-language', 2, 'What does the idiom It''s raining cats and dogs mean?', '["Pets are outside.","It is raining very hard.","It has just stopped raining.","It is drizzling lightly."]'::jsonb),
  ('v5-019', 'vocab', 5, 'figurative-language', 3, 'The classroom was a zoo before the bell rang. This sentence is an example of a:', '["simile","alliteration","metaphor","personification"]'::jsonb),
  ('v5-020', 'vocab', 5, 'academic-words', 2, 'To analyze something means to:', '["hide it","copy it","finish it","examine it closely in parts"]'::jsonb),
  ('v6-001', 'vocab', 6, 'prefixes', 1, 'The prefix mis- in the word misread means:', '["wrongly","again","before","half"]'::jsonb),
  ('v6-002', 'vocab', 6, 'prefixes', 2, 'The prefix inter- in the word interstate means:', '["under","between","against","without"]'::jsonb),
  ('v6-003', 'vocab', 6, 'prefixes', 2, 'The prefix anti- in the word antifreeze means:', '["before","with","against","many"]'::jsonb),
  ('v6-004', 'vocab', 6, 'suffixes', 2, 'The suffix -ology, as in biology, means:', '["fear of","full of","state of","the study of"]'::jsonb),
  ('v6-005', 'vocab', 6, 'suffixes', 2, 'Adding the suffix -ment to the verb agree makes agreement, which is a:', '["noun","adjective","adverb","preposition"]'::jsonb),
  ('v6-006', 'vocab', 6, 'roots', 2, 'The root port, as in transport and export, means:', '["stop","carry","write","look"]'::jsonb),
  ('v6-007', 'vocab', 6, 'roots', 3, 'The root spect, as in inspect and spectator, means:', '["hear","carry","look","break"]'::jsonb),
  ('v6-008', 'vocab', 6, 'roots', 3, 'The prefix tele-, as in telescope, means:', '["near","sound","light","far"]'::jsonb),
  ('v6-009', 'vocab', 6, 'synonyms', 2, 'Which word is a synonym for diligent?', '["hardworking","lazy","curious","nervous"]'::jsonb),
  ('v6-010', 'vocab', 6, 'synonyms', 2, 'Which word means about the same as scarce?', '["plentiful","rare","costly","fragile"]'::jsonb),
  ('v6-011', 'vocab', 6, 'antonyms', 1, 'Which word is the opposite of expand?', '["grow","stretch","shrink","enlarge"]'::jsonb),
  ('v6-012', 'vocab', 6, 'antonyms', 3, 'Which word is the opposite of optimistic?', '["hopeful","cheerful","confident","pessimistic"]'::jsonb),
  ('v6-013', 'vocab', 6, 'multiple-meaning', 2, 'Which meaning of cell fits: Every living thing is made of cells.', '["the basic unit of life","a small prison room","a cell phone","a group of workers"]'::jsonb),
  ('v6-014', 'vocab', 6, 'multiple-meaning', 3, 'In the sentence The current in the river was strong, what does current mean?', '["happening right now","flowing movement of water","up to date","a type of money"]'::jsonb),
  ('v6-015', 'vocab', 6, 'context-clues', 2, 'The detective''s explanation was lucid; everyone understood it right away. What does lucid mean?', '["confusing","long","clear","secret"]'::jsonb),
  ('v6-016', 'vocab', 6, 'context-clues', 3, 'Unlike her gregarious brother, who loved parties, she preferred quiet evenings alone. What does gregarious mean?', '["shy","wealthy","grumpy","sociable"]'::jsonb),
  ('v6-017', 'vocab', 6, 'context-clues', 3, 'The trail had no streams, so the hikers had to conserve water and sipped only a little at a time. What does conserve mean?', '["save by using carefully","waste","boil","carry"]'::jsonb),
  ('v6-018', 'vocab', 6, 'figurative-language', 2, 'Her voice was music to his ears. This means her voice was:', '["very loud","pleasant to hear","out of tune","sleepy"]'::jsonb),
  ('v6-019', 'vocab', 6, 'figurative-language', 3, 'The old car coughed and groaned up the hill. This is an example of:', '["simile","hyperbole","personification","an idiom"]'::jsonb),
  ('v6-020', 'vocab', 6, 'academic-words', 2, 'To contrast two things means to show how they are:', '["the same","connected","equal in size","different"]'::jsonb)
on conflict (id) do update set subject = excluded.subject, grade = excluded.grade, skill = excluded.skill,
  difficulty = excluded.difficulty, prompt = excluded.prompt, choices = excluded.choices;
insert into public.question_keys (question_id, answer, explanation) values
  ('v5-001', 0, 'The prefix un- means not, so unhappy means not happy.'),
  ('v5-002', 1, 'Re- means again, so rewrite means to write again.'),
  ('v5-003', 2, 'Pre- means before, so a preview is a look before the full showing.'),
  ('v5-004', 3, '-less means without, so hopeless means without hope.'),
  ('v5-005', 0, '-able means can be, so readable means can be read.'),
  ('v5-006', 1, 'Aqua is Latin for water, and an aquarium holds water and fish.'),
  ('v5-007', 2, 'Bio means life, and biology is the study of living things.'),
  ('v5-008', 3, 'Enormous means very large, just like huge.'),
  ('v5-009', 0, 'Swift and rapid both mean fast.'),
  ('v5-010', 1, 'Ancient means very old, so its opposite is modern.'),
  ('v5-011', 2, 'A generous person shares freely; a selfish person does not.'),
  ('v5-012', 3, 'A picnic by a river would be on the sloping land beside it.'),
  ('v5-013', 0, 'Here novel is an adjective meaning new and different.'),
  ('v5-014', 1, 'No rain for months is the clue that arid means very dry.'),
  ('v5-015', 2, 'Eating three sandwiches is the clue that he was very hungry.'),
  ('v5-016', 3, 'Standing at the edge for a long time shows she was unwilling.'),
  ('v5-017', 0, 'The phrase compares a hard worker to a bee that is always working.'),
  ('v5-018', 1, 'This idiom is a playful way to say the rain is heavy.'),
  ('v5-019', 2, 'It compares the classroom to a zoo without using like or as.'),
  ('v5-020', 3, 'Analyze means to study the parts of something carefully.'),
  ('v6-001', 0, 'Mis- means wrongly, so misread means read incorrectly.'),
  ('v6-002', 1, 'An interstate highway runs between states.'),
  ('v6-003', 2, 'Anti- means against; antifreeze works against freezing.'),
  ('v6-004', 3, '-ology means the study of, so biology is the study of life.'),
  ('v6-005', 0, '-ment turns a verb into a noun naming an action or result.'),
  ('v6-006', 1, 'Transport means to carry across; port means carry.'),
  ('v6-007', 2, 'A spectator looks at something, and to inspect is to look closely.'),
  ('v6-008', 3, 'A telescope lets you see far away objects.'),
  ('v6-009', 0, 'A diligent person works carefully and steadily.'),
  ('v6-010', 1, 'Scarce means hard to find, which is what rare means.'),
  ('v6-011', 2, 'Expand means to get bigger, so shrink is its opposite.'),
  ('v6-012', 3, 'An optimist expects good things; a pessimist expects bad ones.'),
  ('v6-013', 0, 'In science, a cell is the smallest unit of a living thing.'),
  ('v6-014', 1, 'A river current is water moving in one direction.'),
  ('v6-015', 2, 'Everyone understood right away, so the explanation was clear.'),
  ('v6-016', 3, 'Loving parties is the clue, and unlike signals an opposite.'),
  ('v6-017', 0, 'Sipping only a little shows they were saving their water.'),
  ('v6-018', 1, 'The phrase says the voice was as pleasing as music.'),
  ('v6-019', 2, 'The car is given human actions, coughing and groaning.'),
  ('v6-020', 3, 'Contrast means pointing out differences.')
on conflict (question_id) do update set answer = excluded.answer, explanation = excluded.explanation;
insert into public.questions (id, subject, grade, skill, difficulty, prompt, choices) values
  ('r5-001', 'reading', 5, 'main-idea', 1, 'Honeybees live in large groups called colonies. A single colony can hold thousands of bees, and each bee has a job. Some collect nectar from flowers, some care for the young bees, and some guard the hive from visitors that do not belong. Working together keeps the colony alive through the whole year.

What is the main idea?', '["Honeybees work together in colonies by doing different jobs.","Honeybees only collect nectar.","Guard bees are the most important.","Honeybees live alone."]'::jsonb),
  ('r5-002', 'reading', 5, 'inference', 2, 'Mia grabbed her umbrella and rain boots, then looked out the window at the dark clouds. A cool wind was pushing the leaves across the yard. She checked the clock and hurried out the door to catch the bus.

What can you infer from the passage?', '["It is a sunny day.","It looks like it is going to rain.","Mia has already missed the bus.","Mia is going to bed."]'::jsonb),
  ('r5-003', 'reading', 5, 'sequence', 1, 'Paper airplanes are fun to make, and anyone can learn how. To make one, first fold the paper in half lengthwise. Next, unfold it and fold the top corners to the center. Then fold the edges in again. Finally, fold the wings down, and your plane is ready to fly.

What step comes right after folding the paper in half?', '["Fold the wings down.","Fold the edges in again.","Unfold it and fold the top corners to the center.","Throw the plane."]'::jsonb),
  ('r5-004', 'reading', 5, 'authors-purpose', 2, 'Did you know an octopus has three hearts? Two pump blood to its gills, and one pumps blood to the rest of its body. An octopus can also squeeze through a gap no bigger than its eye. This surprising animal is full of amazing facts.

The author mostly wrote this passage to:', '["tell a made-up story","convince readers to buy a pet","explain how to draw an animal","inform readers about octopuses"]'::jsonb),
  ('r5-005', 'reading', 5, 'theme', 3, 'A turtle kept practicing every day while the others laughed at his slow pace. Rain or shine, he walked a little farther than the day before. Season after season he kept going. At last he crossed the finish line of the long trail, tired but proud.

Which theme fits this story best?', '["Patience and steady effort lead to success.","Fast animals always win.","Laughing at others is fun.","It is best to give up early."]'::jsonb),
  ('r5-006', 'reading', 5, 'vocabulary-in-context', 2, 'The tiny village was remote, miles from any town or highway. No bus stopped there, and the only road was narrow and full of bumps. Visitors needed a full day to reach it, but those who made the trip said the quiet was worth it.

In this passage, what does remote mean?', '["crowded","far away","famous","controlled by a button"]'::jsonb),
  ('r5-007', 'reading', 5, 'cause-effect', 2, 'After a week without rain, the grass in the park turned brown and the pond got smaller. The flowers drooped, and the ducks had less space to swim. Park workers asked visitors to use less water until the weather changed.

What caused the grass to turn brown?', '["Too many visitors","Cold weather","A week without rain","A smaller pond"]'::jsonb),
  ('r5-008', 'reading', 5, 'details', 1, 'The library opens at 9 a.m. on weekdays and 10 a.m. on Saturdays. It is closed on Sundays. Students can borrow up to five books at a time, and they have two weeks to bring them back. A friendly librarian is always ready to help find a good story.

How many books can students borrow at a time?', '["Three","Nine","Ten","Five"]'::jsonb),
  ('r5-009', 'reading', 5, 'main-idea', 2, 'Recycling aluminum cans saves energy. Making a new can from recycled metal uses far less energy than making one from raw materials. It also keeps cans out of landfills, where they would sit for many years. A recycled can can be back on a store shelf in about two months.

What is the passage mostly about?', '["the benefits of recycling aluminum cans","how cans are shaped","why landfills are large","the cost of soda"]'::jsonb),
  ('r5-010', 'reading', 5, 'inference', 3, 'The coach looked at the scoreboard, then smiled as the team ran off the field. Everyone was hugging, and a few players were jumping up and down. Parents in the stands were cheering and waving signs, and someone had already started singing.

What most likely happened?', '["The team lost badly.","The team won the game.","The game was canceled.","The coach quit."]'::jsonb),
  ('r5-011', 'reading', 5, 'sequence', 2, 'Ben had a busy evening. Before dinner, Ben set the table. After eating, he washed the dishes. Later, he did his homework and read for twenty minutes before bed. By the time he turned off the light, he was ready for sleep.

What did Ben do right after eating?', '["He set the table.","He did his homework.","He washed the dishes.","He read before bed."]'::jsonb),
  ('r5-012', 'reading', 5, 'authors-purpose', 2, 'Every student should walk or bike to school when possible. It keeps you healthy, saves money, and helps the air stay clean. It can also be a fun way to talk with friends before the day begins. Try it this week!

What does the author want to do?', '["teach how to fix a bike","tell a funny story","describe a school building","persuade readers to walk or bike to school"]'::jsonb),
  ('r5-013', 'reading', 5, 'theme', 2, 'A young crow was very thirsty, and he found a tall jar with a little water at the bottom. His beak could not reach it. He dropped pebbles into the jar, one at a time, until the water rose high enough to drink. He had not been strong, but he had been clever.

What lesson does this story teach?', '["Thinking cleverly can solve problems.","Strong birds always win.","Never drink from a jar.","Pebbles are heavy."]'::jsonb),
  ('r5-014', 'reading', 5, 'vocabulary-in-context', 3, 'The hikers were weary after climbing all day. Their legs ached and their backpacks felt twice as heavy as they had that morning. They dropped their packs and fell asleep as soon as they lay down.

What does weary mean?', '["excited","very tired","cold","hungry"]'::jsonb),
  ('r5-015', 'reading', 5, 'inference', 2, 'When the other kids teased him, Leo took a deep breath and walked away without a word. His face felt hot, but he did not shout. Later he told his teacher what happened, and she thanked him for coming to her.

What does this show about Leo?', '["He wanted to tease them back.","He did not care.","He handled the problem calmly and responsibly.","He was angry at his teacher."]'::jsonb),
  ('r5-016', 'reading', 5, 'cause-effect', 1, 'A big storm rolled in at dinnertime, with thunder and heavy rain. The power went out during the storm, so the family lit candles and played board games. They laughed and told stories until the lights came back on.

Why did the family light candles?', '["It was someone''s birthday.","The storm ended.","They bought new games.","The power went out."]'::jsonb),
  ('r5-017', 'reading', 5, 'compare-contrast', 2, 'Frogs and toads look alike, but they differ. Frogs have smooth, moist skin and long legs for jumping. Toads have dry, bumpy skin and shorter legs. Frogs usually stay near water, while toads can spend more time on dry land.

How are frogs different from toads?', '["Frogs have smooth skin and toads have bumpy skin.","Frogs have bumpy skin and toads have smooth skin.","Toads have longer legs than frogs.","Frogs have dry skin and toads have moist skin."]'::jsonb),
  ('r5-018', 'reading', 5, 'vocabulary-in-context', 2, 'The chef used fresh herbs to enhance the soup''s flavor. First she tasted the soup and thought it was a little plain. After adding basil, the soup tasted much richer, and everyone at the table asked for a second bowl.

What does enhance mean?', '["hide","improve","cool down","spill"]'::jsonb),
  ('r5-019', 'reading', 5, 'main-idea', 3, 'Many people think deserts are empty, but they hold plenty of life. Cacti store water in their thick stems, lizards hide in cool burrows by day, and owls hunt after dark when the air is cooler. Even tiny seeds wait in the sand for rain. Each living thing is suited to dry heat.

What is the main idea?', '["Deserts are empty.","Owls are the best hunters.","Desert life has ways to survive in dry places.","Cacti are very tall."]'::jsonb),
  ('r5-020', 'reading', 5, 'inference', 3, 'A sign at the pool reads: Walk, don''t run. Wet floors are slippery. Please shower before swimming. Another sign by the deep end reminds swimmers to ask a lifeguard before they dive. The pool is open every afternoon after school.

Why does the sign say Walk, don''t run?', '["Because the pool is far away","To help swimmers swim faster","Because walking is more fun","To keep people from slipping"]'::jsonb),
  ('r6-001', 'reading', 6, 'main-idea', 1, 'Volcanoes form when melted rock from deep inside Earth rises to the surface. Over time, layers of cooled lava and ash pile up and build a mountain. The process can take thousands of years. Some volcanoes are still active today, and scientists watch them closely.

What is the main idea?', '["Rising melted rock builds volcanoes over time.","All volcanoes are active.","Ash harms plants.","Mountains form overnight."]'::jsonb),
  ('r6-002', 'reading', 6, 'inference', 2, 'The cafeteria was unusually quiet. Students stared at their trays, and the usual chatter was gone. Nobody was trading snacks or telling jokes. A few kept glancing at the clock, waiting for the announcement about test scores.

How do the students probably feel?', '["excited about a party","nervous about the results","bored with lunch","angry at the cooks"]'::jsonb),
  ('r6-003', 'reading', 6, 'authors-purpose', 2, 'The bright yellow lemon looked cheerful on the counter, sitting beside a bowl of green apples. Its skin was bumpy and smelled sweetly sour, like sunshine in a bottle. Even before it was cut, the whole kitchen seemed a little brighter.

Why does the author write sunshine in a bottle?', '["to prove lemons need sun","to explain how to make juice","to help readers imagine the smell","to compare prices"]'::jsonb),
  ('r6-004', 'reading', 6, 'sequence', 2, 'The sea turtle crawled from the water and dug a hole in the sand. She laid her eggs, covered them, and returned to the sea. The sun warmed the sand for weeks. Later, the hatchlings dug out and scurried to the waves, guided by the shining water.

What happens right after she lays her eggs?', '["The hatchlings reach the waves.","She digs a hole.","The hatchlings dig out.","She covers them with sand."]'::jsonb),
  ('r6-005', 'reading', 6, 'theme', 3, 'Everyone said the old bridge could not be fixed. It sagged in the middle, and half its boards were gone. Neighbors brought boards, tools, and lunches anyway. They worked side by side all day. By sunset, they had rebuilt it, and everyone crossed together.

Which theme fits this story?', '["Working together can accomplish hard goals.","Old things should be thrown away.","Bridges are easy to build.","Lunch is the most important part of work."]'::jsonb),
  ('r6-006', 'reading', 6, 'vocabulary-in-context', 2, 'The lawyer''s argument was so compelling that the jury listened without moving. Not a single person looked at the clock or whispered to a neighbor. When she finished, the room stayed silent for a moment. Many members changed their minds.

What does compelling mean?', '["confusing","convincing","lengthy","rude"]'::jsonb),
  ('r6-007', 'reading', 6, 'cause-effect', 2, 'The factory had been the center of the town for fifty years. When the factory closed, many families moved away. With fewer customers, the town''s shops lost business, and several closed too. Soon, the busy main street felt much quieter.

What was a result of fewer customers?', '["The factory closed.","More families moved in.","Several shops closed.","The factory reopened."]'::jsonb),
  ('r6-008', 'reading', 6, 'authors-purpose', 1, 'Our class garden needs volunteers! The beds are full of weeds, and the new seeds have not gone in yet. Join us Saturday at 9 a.m. to plant seeds and pull weeds. Bring gloves and a water bottle. We will finish by lunchtime, and snacks will be provided.

What is the main purpose of this passage?', '["to explain how seeds grow","to tell about a past trip","to describe weeds","to invite readers to help"]'::jsonb),
  ('r6-009', 'reading', 6, 'main-idea', 2, 'Sleep is important for growing students. During sleep, the body repairs itself and the brain stores new memories. Sleeping well can also help your mood stay steady during a long school day. Students who sleep nine to eleven hours often do better in class.

Which sentence best summarizes the passage?', '["Enough sleep helps the body and the brain.","Students should skip homework.","Memory only works during class.","Sleep is only for adults."]'::jsonb),
  ('r6-010', 'reading', 6, 'inference', 3, 'The path was covered with small paw prints that led to the edge of the pond. The prints looked fresh, with sharp edges in the damp soil. Near the water, the mud was churned up, and a few feathers floated nearby.

What can you infer?', '["No animals live nearby.","An animal visited the pond recently.","The pond froze solid.","People built the path yesterday."]'::jsonb),
  ('r6-011', 'reading', 6, 'vocabulary-in-context', 3, 'The scientist''s theory was tentative. Her first experiment had gone well, but one result still surprised her. She wrote in her notebook that the idea might change. The theory was tentative, so she planned more experiments before announcing it as fact.

What does tentative mean?', '["final","secret","not yet certain","famous"]'::jsonb),
  ('r6-012', 'reading', 6, 'sequence', 1, 'The students wanted to learn which birds visited the school feeder. First, the team gathered data on bird visits. Then they graphed the results. Last, they wrote a summary to share with the class and hung it on the science wall.

What did the team do second?', '["They gathered data.","They wrote a summary.","They fed the birds.","They graphed the results."]'::jsonb),
  ('r6-013', 'reading', 6, 'theme', 2, 'The little fox ran hard, but she lost the race by a few steps. She was disappointed, though she did not sulk. Though the little fox lost the race, she congratulated the winner and asked for tips. Next time, she trained with them and ran her best time yet.

Which theme fits this story?', '["Learning from setbacks leads to growth.","Winning is everything.","Losing is shameful.","Foxes are fast."]'::jsonb),
  ('r6-014', 'reading', 6, 'cause-effect', 3, 'Mangrove trees grow along warm coastlines, with tangled roots that rise out of the water. Because mangrove roots trap soil, coastlines with mangroves lose less land to waves. They also give young fish a safe place to hide. When people cut the trees down, shores often wash away faster.

What happens when mangroves are cut down?', '["Roots trap more soil.","Shores may wash away faster.","Waves stop.","Coastlines grow."]'::jsonb),
  ('r6-015', 'reading', 6, 'compare-contrast', 2, 'Both lakes and ponds hold fresh water, and both are home to fish, frogs, and plants. Lakes are generally larger and deeper, while ponds are shallow enough for sunlight to reach the bottom. Because of that, plants can grow across a whole pond.

How is a pond different from a lake?', '["Ponds are salty.","Ponds are deeper.","Ponds are generally shallower.","Ponds get no sunlight."]'::jsonb),
  ('r6-016', 'reading', 6, 'mood', 2, 'The old house stood alone on the hill, its windows dark and its shutters creaking in the wind. Weeds had grown up through the porch, and a loose gate swung back and forth. No one had lived there for years.

What mood does the author create?', '["cheerful and busy","angry and loud","excited and proud","lonely and eerie"]'::jsonb),
  ('r6-017', 'reading', 6, 'main-idea', 3, 'Coral reefs cover less than one percent of the ocean floor, yet about a quarter of ocean species depend on them. Reefs give fish food and places to hide. Warming water can cause corals to lose color and weaken. Protecting reefs protects countless animals.

What is the main idea?', '["Coral reefs support many species and need protection.","Reefs cover most of the ocean.","Corals love warm water.","Fish are colorful."]'::jsonb),
  ('r6-018', 'reading', 6, 'inference', 2, 'Rosa wanted to see how fast a bean plant could grow. She measured it each Monday and wrote the number in her science journal. It was 4 cm in week one, 7 cm in week two, and 10 cm in week three. She kept it on a sunny windowsill and watered it each morning.

If the pattern continues, how tall will it be in week four?', '["11 cm","13 cm","12 cm","14 cm"]'::jsonb),
  ('r6-019', 'reading', 6, 'vocabulary-in-context', 2, 'The farmer let the field lie fallow for a year. Instead of planting corn as usual, she left it unplanted so the soil could rest. Wildflowers grew along the edges, and the soil slowly became richer for the next season.

What does fallow mean?', '["newly planted","covered in snow","left unplanted","used for animals"]'::jsonb),
  ('r6-020', 'reading', 6, 'character', 3, 'Though some call him a hero, the lighthouse keeper simply said, I just lit the lamp every night. He never asked for thanks. Ships passed safely along the rocky coast, and few of the sailors ever learned his name. He quietly kept working for forty years.

What does this show about the keeper?', '["He is proud of his fame.","He wanted rewards.","He disliked his work.","He is humble."]'::jsonb)
on conflict (id) do update set subject = excluded.subject, grade = excluded.grade, skill = excluded.skill,
  difficulty = excluded.difficulty, prompt = excluded.prompt, choices = excluded.choices;
insert into public.question_keys (question_id, answer, explanation) values
  ('r5-001', 0, 'The passage says each bee has a job and that teamwork keeps the colony alive.'),
  ('r5-002', 1, 'The umbrella, boots and dark clouds are clues that rain is likely.'),
  ('r5-003', 2, 'The word next tells us the step after the first fold is unfolding and folding the corners.'),
  ('r5-004', 3, 'The passage shares facts, so the author''s purpose is to inform.'),
  ('r5-005', 0, 'The turtle succeeds because he keeps working, even when others laugh.'),
  ('r5-006', 1, 'Miles from any town and a full day to reach it show that remote means far away.'),
  ('r5-007', 2, 'The passage says the grass turned brown after a week without rain.'),
  ('r5-008', 3, 'The last sentence states students can borrow up to five books.'),
  ('r5-009', 0, 'Every sentence explains a benefit of recycling aluminum cans.'),
  ('r5-010', 1, 'Smiling, hugging and jumping are clues that the team was celebrating a win.'),
  ('r5-011', 2, 'The passage says that after eating, Ben washed the dishes.'),
  ('r5-012', 3, 'The author gives reasons and urges readers to try it, which is persuading.'),
  ('r5-013', 0, 'The crow solved its problem with a smart idea instead of strength.'),
  ('r5-014', 1, 'Falling asleep right away is the clue that they were very tired.'),
  ('r5-015', 2, 'Walking away calmly and telling a teacher shows responsible behavior.'),
  ('r5-016', 3, 'The word so shows the power outage caused the candles to be lit.'),
  ('r5-017', 0, 'The passage says frogs have smooth, moist skin and toads have dry, bumpy skin.'),
  ('r5-018', 1, 'The soup tasted richer, so enhance means to make better.'),
  ('r5-019', 2, 'The examples all show how desert life is suited to the dry heat.'),
  ('r5-020', 3, 'The next sentence explains that wet floors are slippery.'),
  ('r6-001', 0, 'The passage mostly explains how volcanoes are formed.'),
  ('r6-002', 1, 'Quiet students waiting for test scores are most likely nervous.'),
  ('r6-003', 2, 'The comparison is a descriptive image that helps readers picture the scent.'),
  ('r6-004', 3, 'The passage lists covering the eggs right after laying them.'),
  ('r6-005', 0, 'The neighbors achieved the goal by cooperating.'),
  ('r6-006', 1, 'The jurors changed their minds, so the argument was convincing.'),
  ('r6-007', 2, 'The passage says shops lost business and several closed.'),
  ('r6-008', 3, 'The author asks readers to join and gives details for volunteering.'),
  ('r6-009', 0, 'The passage gives reasons sleep helps both body and brain.'),
  ('r6-010', 1, 'Fresh paw prints, churned mud and feathers show an animal was there.'),
  ('r6-011', 2, 'She needed more tests, so the theory was not yet certain.'),
  ('r6-012', 3, 'The word then marks graphing as the second step.'),
  ('r6-013', 0, 'The fox improved by learning from her loss.'),
  ('r6-014', 1, 'The passage states shores often wash away faster without the trees.'),
  ('r6-015', 2, 'The passage says ponds are shallow enough for sunlight to reach the bottom.'),
  ('r6-016', 3, 'Dark windows, creaking shutters and emptiness create a lonely, eerie feeling.'),
  ('r6-017', 0, 'The passage stresses how important reefs are to ocean life and why protect them.'),
  ('r6-018', 1, 'The plant grows 3 cm each week, so 10 + 3 = 13.'),
  ('r6-019', 2, 'The passage explains the field was left unplanted.'),
  ('r6-020', 3, 'Downplaying his role and not asking for thanks shows humility.')
on conflict (question_id) do update set answer = excluded.answer, explanation = excluded.explanation;
insert into public.questions (id, subject, grade, skill, difficulty, prompt, choices) values
  ('s5-001', 'science', 5, 'life-science', 1, 'Which part of a plant takes in water from the soil?', '["roots","leaves","petals","stem"]'::jsonb),
  ('s5-002', 'science', 5, 'life-science', 2, 'What is the process plants use to make food from sunlight, water and carbon dioxide?', '["evaporation","photosynthesis","digestion","pollination"]'::jsonb),
  ('s5-003', 'science', 5, 'life-science', 2, 'In a food chain, what is a producer?', '["an animal that eats only meat","an organism that breaks down dead things","a plant that makes its own food","an animal that eats plants"]'::jsonb),
  ('s5-004', 'science', 5, 'life-science', 2, 'Animals that eat only plants are called:', '["carnivores","omnivores","decomposers","herbivores"]'::jsonb),
  ('s5-005', 'science', 5, 'life-science', 3, 'Which adaptation helps a polar bear stay warm in the Arctic?', '["a thick layer of fat and fur","long legs for running","bright feathers","gills"]'::jsonb),
  ('s5-006', 'science', 5, 'earth-science', 1, 'What is the name for water falling from clouds as rain, snow or hail?', '["evaporation","precipitation","condensation","collection"]'::jsonb),
  ('s5-007', 'science', 5, 'earth-science', 2, 'Water vapor cooling into tiny droplets to form clouds is called:', '["evaporation","erosion","condensation","precipitation"]'::jsonb),
  ('s5-008', 'science', 5, 'earth-science', 2, 'Which type of rock forms when melted rock cools and hardens?', '["sedimentary","metamorphic","fossil","igneous"]'::jsonb),
  ('s5-009', 'science', 5, 'earth-science', 3, 'Which process moves bits of rock and soil from one place to another by wind or water?', '["erosion","condensation","germination","reflection"]'::jsonb),
  ('s5-010', 'science', 5, 'physical-science', 1, 'Which state of matter has a definite shape and a definite volume?', '["liquid","solid","gas","steam"]'::jsonb),
  ('s5-011', 'science', 5, 'physical-science', 2, 'What happens to water molecules as water is heated to boiling?', '["They stop moving.","They move slower.","They move faster and become a gas.","They disappear."]'::jsonb),
  ('s5-012', 'science', 5, 'physical-science', 2, 'Which object is the best conductor of heat?', '["a wooden spoon","a foam cup","a plastic handle","a metal spoon"]'::jsonb),
  ('s5-013', 'science', 5, 'physical-science', 3, 'A ball rolling across grass slows to a stop mainly because of:', '["friction","magnetism","light","evaporation"]'::jsonb),
  ('s5-014', 'science', 5, 'space', 1, 'What is the closest star to Earth?', '["the Moon","the Sun","Polaris","Mars"]'::jsonb),
  ('s5-015', 'science', 5, 'space', 2, 'Why do we have day and night?', '["Earth orbits the Sun once a day.","The Moon blocks the Sun.","Earth rotates on its axis.","The Sun moves around Earth."]'::jsonb),
  ('s5-016', 'science', 5, 'space', 2, 'Which planet is the largest in our solar system?', '["Saturn","Earth","Neptune","Jupiter"]'::jsonb),
  ('s5-017', 'science', 5, 'scientific-method', 2, 'A student tests how sunlight affects plant growth. What should stay the same for all plants?', '["the amount of water each plant gets","the amount of light each plant gets","the final height of each plant","the conclusion"]'::jsonb),
  ('s5-018', 'science', 5, 'scientific-method', 1, 'A testable prediction made before an experiment is called a:', '["conclusion","hypothesis","data table","observation"]'::jsonb),
  ('s5-019', 'science', 5, 'measurement', 1, 'Which tool measures temperature?', '["ruler","balance","thermometer","barometer"]'::jsonb),
  ('s5-020', 'science', 5, 'measurement', 2, 'Which unit is used to measure the volume of a liquid?', '["grams","centimeters","degrees","milliliters"]'::jsonb),
  ('s6-001', 'science', 6, 'life-science', 1, 'What is the basic unit of life?', '["cell","tissue","organ","atom"]'::jsonb),
  ('s6-002', 'science', 6, 'life-science', 2, 'Which structure gives a plant cell a rigid outer layer for support?', '["nucleus","cell wall","chloroplast","cytoplasm"]'::jsonb),
  ('s6-003', 'science', 6, 'life-science', 2, 'What is the main job of the mitochondria in a cell?', '["make food from sunlight","store the cell''s nucleus","release usable energy from food","control the cell''s color"]'::jsonb),
  ('s6-004', 'science', 6, 'life-science', 3, 'Which organisms break down dead material and return nutrients to the soil?', '["producers","herbivores","predators","decomposers"]'::jsonb),
  ('s6-005', 'science', 6, 'life-science', 2, 'Which is an example of an inherited trait?', '["eye color","a scar","knowing how to ride a bike","a short haircut"]'::jsonb),
  ('s6-006', 'science', 6, 'earth-science', 1, 'On which layer of Earth do we live?', '["mantle","crust","outer core","inner core"]'::jsonb),
  ('s6-007', 'science', 6, 'earth-science', 2, 'Where do most earthquakes happen?', '["in the middle of large flat plains","only in deserts","where tectonic plates meet","deep inside Earth''s core"]'::jsonb),
  ('s6-008', 'science', 6, 'earth-science', 2, 'Where is most of Earth''s surface water found?', '["in lakes","in rivers","in the air","in the oceans"]'::jsonb),
  ('s6-009', 'science', 6, 'earth-science', 3, 'What causes the seasons on Earth?', '["the tilt of Earth''s axis","Earth moving much closer to and farther from the Sun","the phases of the Moon","clouds blocking the Sun"]'::jsonb),
  ('s6-010', 'science', 6, 'earth-science', 2, 'Which of these is a fossil fuel?', '["solar energy","coal","wind","hydropower"]'::jsonb),
  ('s6-011', 'science', 6, 'physical-science', 1, 'Which unit is used to measure force?', '["gram","meter","newton","liter"]'::jsonb),
  ('s6-012', 'science', 6, 'physical-science', 2, 'A car travels 150 km in 3 hours at a steady speed. What is its speed?', '["450 km/h","153 km/h","30 km/h","50 km/h"]'::jsonb),
  ('s6-013', 'science', 6, 'physical-science', 2, 'A rocket moves upward as gases push downward. This shows that:', '["for every action there is an equal and opposite reaction","objects at rest stay at rest forever","heavier objects always fall faster","energy can be created"]'::jsonb),
  ('s6-014', 'science', 6, 'physical-science', 3, 'Which is an example of a chemical change?', '["melting ice","burning wood","tearing paper","crushing a can"]'::jsonb),
  ('s6-015', 'science', 6, 'physical-science', 2, 'What is the energy of motion called?', '["potential energy","chemical energy","kinetic energy","nuclear energy"]'::jsonb),
  ('s6-016', 'science', 6, 'physical-science', 3, 'Which of these is a mixture?', '["pure water","oxygen gas","pure iron","salt dissolved in water"]'::jsonb),
  ('s6-017', 'science', 6, 'space', 2, 'What causes the phases of the Moon?', '["how much of its sunlit side we can see as it orbits Earth","Earth''s shadow covering it","clouds in the sky","the Moon changing size"]'::jsonb),
  ('s6-018', 'science', 6, 'space', 1, 'Which planet is closest to the Sun?', '["Venus","Mercury","Mars","Earth"]'::jsonb),
  ('s6-019', 'science', 6, 'scientific-method', 3, 'Why do scientists repeat experiments?', '["to make the experiment longer","to change their hypothesis","to check that results are reliable","to be sure they win"]'::jsonb),
  ('s6-020', 'science', 6, 'measurement', 2, 'A rock has a mass of 250 grams. How many kilograms is that?', '["2.5 kg","25 kg","0.025 kg","0.25 kg"]'::jsonb)
on conflict (id) do update set subject = excluded.subject, grade = excluded.grade, skill = excluded.skill,
  difficulty = excluded.difficulty, prompt = excluded.prompt, choices = excluded.choices;
insert into public.question_keys (question_id, answer, explanation) values
  ('s5-001', 0, 'Roots absorb water and nutrients from the soil.'),
  ('s5-002', 1, 'Photosynthesis uses light energy to make sugar.'),
  ('s5-003', 2, 'Producers, such as plants, make their own food using sunlight.'),
  ('s5-004', 3, 'Herbivore means plant eater.'),
  ('s5-005', 0, 'Fat and thick fur insulate the bear from the cold.'),
  ('s5-006', 1, 'Precipitation is any water that falls from clouds.'),
  ('s5-007', 2, 'Condensation is when a gas cools and becomes liquid.'),
  ('s5-008', 3, 'Igneous rock forms from cooled magma or lava.'),
  ('s5-009', 0, 'Erosion carries sediment away.'),
  ('s5-010', 1, 'Solids keep their own shape and volume.'),
  ('s5-011', 2, 'Heat energy makes molecules move faster until they escape as vapor.'),
  ('s5-012', 3, 'Metals let heat move through them easily.'),
  ('s5-013', 0, 'Friction between the ball and the grass opposes its motion.'),
  ('s5-014', 1, 'The Sun is our nearest star.'),
  ('s5-015', 2, 'As Earth spins, different places face toward or away from the Sun.'),
  ('s5-016', 3, 'Jupiter is bigger than all other planets.'),
  ('s5-017', 0, 'Only one variable (light) should change, so water must stay the same.'),
  ('s5-018', 1, 'A hypothesis is a prediction you can test.'),
  ('s5-019', 2, 'A thermometer measures how hot or cold something is.'),
  ('s5-020', 3, 'Milliliters measure how much space a liquid takes up.'),
  ('s6-001', 0, 'All living things are made of one or more cells.'),
  ('s6-002', 1, 'The cell wall surrounds plant cells and keeps them firm.'),
  ('s6-003', 2, 'Mitochondria release energy the cell can use.'),
  ('s6-004', 3, 'Decomposers like fungi and bacteria recycle nutrients.'),
  ('s6-005', 0, 'Eye color is passed from parents to offspring in genes.'),
  ('s6-006', 1, 'The crust is Earth''s thin, solid outer layer.'),
  ('s6-007', 2, 'Earthquakes mostly occur along plate boundaries where plates move.'),
  ('s6-008', 3, 'About 97 percent of Earth''s water is in the oceans.'),
  ('s6-009', 0, 'The tilt changes how directly sunlight hits each part of Earth during the year.'),
  ('s6-010', 1, 'Coal formed from ancient plants over millions of years.'),
  ('s6-011', 2, 'The newton is the standard unit of force.'),
  ('s6-012', 3, 'Speed = distance divided by time = 150 / 3 = 50.'),
  ('s6-013', 0, 'The downward push of the gas causes an upward push on the rocket.'),
  ('s6-014', 1, 'Burning makes new substances like ash and gases.'),
  ('s6-015', 2, 'Kinetic energy is the energy an object has because it is moving.'),
  ('s6-016', 3, 'Salt water is two substances mixed but not chemically combined.'),
  ('s6-017', 0, 'As the Moon orbits, we see different amounts of its lit half.'),
  ('s6-018', 1, 'Mercury orbits nearest the Sun.'),
  ('s6-019', 2, 'Repeated trials that match show the results are trustworthy.'),
  ('s6-020', 3, 'There are 1,000 grams in a kilogram, so 250 / 1000 = 0.25.')
on conflict (question_id) do update set answer = excluded.answer, explanation = excluded.explanation;
