-- Reading passages are about 1.7 times longer. Only the passage part of each prompt changes; the question line after the blank line stays.
update public.questions q set prompt = v.p || E'\n\n' || regexp_replace(q.prompt, '^.*\n\n', '')
  from (values
('r5-001', $p$Honeybees live in large groups called colonies. A single colony can hold thousands of bees, and each bee has a job. Some collect nectar from flowers, some care for the young bees, and some guard the hive from visitors that do not belong. Working together keeps the colony alive through the whole year.$p$),
('r5-002', $p$Mia grabbed her umbrella and rain boots, then looked out the window at the dark clouds. A cool wind was pushing the leaves across the yard. She checked the clock and hurried out the door to catch the bus.$p$),
('r5-003', $p$Paper airplanes are fun to make, and anyone can learn how. To make one, first fold the paper in half lengthwise. Next, unfold it and fold the top corners to the center. Then fold the edges in again. Finally, fold the wings down, and your plane is ready to fly.$p$),
('r5-004', $p$Did you know an octopus has three hearts? Two pump blood to its gills, and one pumps blood to the rest of its body. An octopus can also squeeze through a gap no bigger than its eye. This surprising animal is full of amazing facts.$p$),
('r5-005', $p$A turtle kept practicing every day while the others laughed at his slow pace. Rain or shine, he walked a little farther than the day before. Season after season he kept going. At last he crossed the finish line of the long trail, tired but proud.$p$),
('r5-006', $p$The tiny village was remote, miles from any town or highway. No bus stopped there, and the only road was narrow and full of bumps. Visitors needed a full day to reach it, but those who made the trip said the quiet was worth it.$p$),
('r5-007', $p$After a week without rain, the grass in the park turned brown and the pond got smaller. The flowers drooped, and the ducks had less space to swim. Park workers asked visitors to use less water until the weather changed.$p$),
('r5-008', $p$The library opens at 9 a.m. on weekdays and 10 a.m. on Saturdays. It is closed on Sundays. Students can borrow up to five books at a time, and they have two weeks to bring them back. A friendly librarian is always ready to help find a good story.$p$),
('r5-009', $p$Recycling aluminum cans saves energy. Making a new can from recycled metal uses far less energy than making one from raw materials. It also keeps cans out of landfills, where they would sit for many years. A recycled can can be back on a store shelf in about two months.$p$),
('r5-010', $p$The coach looked at the scoreboard, then smiled as the team ran off the field. Everyone was hugging, and a few players were jumping up and down. Parents in the stands were cheering and waving signs, and someone had already started singing.$p$),
('r5-011', $p$Ben had a busy evening. Before dinner, Ben set the table. After eating, he washed the dishes. Later, he did his homework and read for twenty minutes before bed. By the time he turned off the light, he was ready for sleep.$p$),
('r5-012', $p$Every student should walk or bike to school when possible. It keeps you healthy, saves money, and helps the air stay clean. It can also be a fun way to talk with friends before the day begins. Try it this week!$p$),
('r5-013', $p$A young crow was very thirsty, and he found a tall jar with a little water at the bottom. His beak could not reach it. He dropped pebbles into the jar, one at a time, until the water rose high enough to drink. He had not been strong, but he had been clever.$p$),
('r5-014', $p$The hikers were weary after climbing all day. Their legs ached and their backpacks felt twice as heavy as they had that morning. They dropped their packs and fell asleep as soon as they lay down.$p$),
('r5-015', $p$When the other kids teased him, Leo took a deep breath and walked away without a word. His face felt hot, but he did not shout. Later he told his teacher what happened, and she thanked him for coming to her.$p$),
('r5-016', $p$A big storm rolled in at dinnertime, with thunder and heavy rain. The power went out during the storm, so the family lit candles and played board games. They laughed and told stories until the lights came back on.$p$),
('r5-017', $p$Frogs and toads look alike, but they differ. Frogs have smooth, moist skin and long legs for jumping. Toads have dry, bumpy skin and shorter legs. Frogs usually stay near water, while toads can spend more time on dry land.$p$),
('r5-018', $p$The chef used fresh herbs to enhance the soup's flavor. First she tasted the soup and thought it was a little plain. After adding basil, the soup tasted much richer, and everyone at the table asked for a second bowl.$p$),
('r5-019', $p$Many people think deserts are empty, but they hold plenty of life. Cacti store water in their thick stems, lizards hide in cool burrows by day, and owls hunt after dark when the air is cooler. Even tiny seeds wait in the sand for rain. Each living thing is suited to dry heat.$p$),
('r5-020', $p$A sign at the pool reads: Walk, don't run. Wet floors are slippery. Please shower before swimming. Another sign by the deep end reminds swimmers to ask a lifeguard before they dive. The pool is open every afternoon after school.$p$)
) as v(id, p) where q.id = v.id;
update public.questions q set prompt = v.p || E'\n\n' || regexp_replace(q.prompt, '^.*\n\n', '')
  from (values
('r6-001', $p$Volcanoes form when melted rock from deep inside Earth rises to the surface. Over time, layers of cooled lava and ash pile up and build a mountain. The process can take thousands of years. Some volcanoes are still active today, and scientists watch them closely.$p$),
('r6-002', $p$The cafeteria was unusually quiet. Students stared at their trays, and the usual chatter was gone. Nobody was trading snacks or telling jokes. A few kept glancing at the clock, waiting for the announcement about test scores.$p$),
('r6-003', $p$The bright yellow lemon looked cheerful on the counter, sitting beside a bowl of green apples. Its skin was bumpy and smelled sweetly sour, like sunshine in a bottle. Even before it was cut, the whole kitchen seemed a little brighter.$p$),
('r6-004', $p$The sea turtle crawled from the water and dug a hole in the sand. She laid her eggs, covered them, and returned to the sea. The sun warmed the sand for weeks. Later, the hatchlings dug out and scurried to the waves, guided by the shining water.$p$),
('r6-005', $p$Everyone said the old bridge could not be fixed. It sagged in the middle, and half its boards were gone. Neighbors brought boards, tools, and lunches anyway. They worked side by side all day. By sunset, they had rebuilt it, and everyone crossed together.$p$),
('r6-006', $p$The lawyer's argument was so compelling that the jury listened without moving. Not a single person looked at the clock or whispered to a neighbor. When she finished, the room stayed silent for a moment. Many members changed their minds.$p$),
('r6-007', $p$The factory had been the center of the town for fifty years. When the factory closed, many families moved away. With fewer customers, the town's shops lost business, and several closed too. Soon, the busy main street felt much quieter.$p$),
('r6-008', $p$Our class garden needs volunteers! The beds are full of weeds, and the new seeds have not gone in yet. Join us Saturday at 9 a.m. to plant seeds and pull weeds. Bring gloves and a water bottle. We will finish by lunchtime, and snacks will be provided.$p$),
('r6-009', $p$Sleep is important for growing students. During sleep, the body repairs itself and the brain stores new memories. Sleeping well can also help your mood stay steady during a long school day. Students who sleep nine to eleven hours often do better in class.$p$),
('r6-010', $p$The path was covered with small paw prints that led to the edge of the pond. The prints looked fresh, with sharp edges in the damp soil. Near the water, the mud was churned up, and a few feathers floated nearby.$p$),
('r6-011', $p$The scientist's theory was tentative. Her first experiment had gone well, but one result still surprised her. She wrote in her notebook that the idea might change. The theory was tentative, so she planned more experiments before announcing it as fact.$p$),
('r6-012', $p$The students wanted to learn which birds visited the school feeder. First, the team gathered data on bird visits. Then they graphed the results. Last, they wrote a summary to share with the class and hung it on the science wall.$p$),
('r6-013', $p$The little fox ran hard, but she lost the race by a few steps. She was disappointed, though she did not sulk. Though the little fox lost the race, she congratulated the winner and asked for tips. Next time, she trained with them and ran her best time yet.$p$),
('r6-014', $p$Mangrove trees grow along warm coastlines, with tangled roots that rise out of the water. Because mangrove roots trap soil, coastlines with mangroves lose less land to waves. They also give young fish a safe place to hide. When people cut the trees down, shores often wash away faster.$p$),
('r6-015', $p$Both lakes and ponds hold fresh water, and both are home to fish, frogs, and plants. Lakes are generally larger and deeper, while ponds are shallow enough for sunlight to reach the bottom. Because of that, plants can grow across a whole pond.$p$),
('r6-016', $p$The old house stood alone on the hill, its windows dark and its shutters creaking in the wind. Weeds had grown up through the porch, and a loose gate swung back and forth. No one had lived there for years.$p$),
('r6-017', $p$Coral reefs cover less than one percent of the ocean floor, yet about a quarter of ocean species depend on them. Reefs give fish food and places to hide. Warming water can cause corals to lose color and weaken. Protecting reefs protects countless animals.$p$),
('r6-018', $p$Rosa wanted to see how fast a bean plant could grow. She measured it each Monday and wrote the number in her science journal. It was 4 cm in week one, 7 cm in week two, and 10 cm in week three. She kept it on a sunny windowsill and watered it each morning.$p$),
('r6-019', $p$The farmer let the field lie fallow for a year. Instead of planting corn as usual, she left it unplanted so the soil could rest. Wildflowers grew along the edges, and the soil slowly became richer for the next season.$p$),
('r6-020', $p$Though some call him a hero, the lighthouse keeper simply said, I just lit the lamp every night. He never asked for thanks. Ships passed safely along the rocky coast, and few of the sailors ever learned his name. He quietly kept working for forty years.$p$)
) as v(id, p) where q.id = v.id;
